dubbo:
  application:
    name: boot-duboo-consumer
  # 指定注册协议和注册地址  dubbo推荐使用zookeeper作为注册中心，并且在start依赖中引入了zookeeper的java客户端Curator
  registry:
    protocol: zookeeper
    address: 47.104.188.96:2181
  protocol.name: dubbo
  # 关闭所有服务的启动时检查 (没有提供者时报错）视实际情况设置
  consumer:
    check: false
server:
  port: 8090