server:
  port: 8102
eureka:
  client:
    register-with-eureka: false # false表示不能向注册中心注册自己。
    service-url:
      defaultZone: http://erueka7001.com:7001/eureka/,http://erueka7002.com:7002/eureka/,http://erueka7003.com:7003/eureka/

feign:
  hystrix:
    enabled: true # 启动Feign对Hystrix的支持