
spring:
  mail:
    username: xxxxxxxxx@qq.com
    password: wtugwsolfrbrbbib
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true # 以qq邮箱为服务器，需要设置ssl为true