server:
  port: 3344
spring:
  application:
    name: cloudserver-config
  cloud:
    config:
      server:
        git:
          uri: https:/git@github.com:mister-shen/javalearn.git #github上面的git仓库地址
