server:
  port: 7001
eureka:
  instance:
    hostname: erueka7001.com         # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不能向注册中心注册自己。
    fetch-registry: false       # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务。
    service-url:
      # 单机
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与Eureka Server交互的地址查询服务于注册服务
      # 集群
      defaultZone: http://erueka7001.com:7001/eureka/,http://erueka7002.com:7002/eureka/
#  server:
#    enable-self-preservation: false   # 禁用eureka自我保护机制（生产环境不建议使用）


