
spring:
  application:
    name: consumer-user
server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true # \u6CE8\u518C\u670D\u52A1\u7684\u65F6\u5019\u4F7F\u7528ip\u5730\u5740\u6CE8\u518C
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/